"use client"
import { useState } from 'react'
import { useAuth } from '@/contexts/auth-context'
import { authApi } from '@/lib/api-client'
import { User, Mail, Phone, Check, Pencil, Loader2, LogOut } from 'lucide-react'
import { toast } from 'sonner'
export function SettingsContent() {
  const { user, logout, refreshUser } = useAuth()
  const [isEditing, setIsEditing] = useState(false)
  const [editedProfile, setEditedProfile] = useState({ name: user?.name ?? '', phone: user?.phone ?? '' })
  const [isSaving, setIsSaving] = useState(false)
  const handleSave = async () => { setIsSaving(true); try { await authApi.updateProfile(editedProfile); await refreshUser(); setIsEditing(false); toast.success('Профиль обновлён') } catch (err) { toast.error(err instanceof Error ? err.message : 'Ошибка') } finally { setIsSaving(false) } }
  if (!user) return null
  return (<div className="flex-1 bg-background overflow-auto"><div className="max-w-2xl mx-auto p-8"><div className="mb-8"><h1 className="text-2xl font-semibold">Настройки профиля</h1><p className="text-muted-foreground mt-1">Управление данными аккаунта</p></div><div className="bg-card rounded-xl border border-border p-6 mb-6"><div className="flex items-center justify-between mb-6"><div className="flex items-center gap-4"><div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center"><User className="w-8 h-8 text-primary" /></div><div><h2 className="font-semibold text-lg">{user.name ?? 'Без имени'}</h2><p className="text-sm text-muted-foreground">{user.email}</p></div></div>{!isEditing&&<button onClick={()=>{setIsEditing(true);setEditedProfile({name:user.name??'',phone:user.phone??''})}} className="flex items-center gap-2 px-3 py-2 rounded-lg border border-input bg-background text-sm hover:bg-secondary"><Pencil className="w-4 h-4" />Редактировать</button>}</div>{isEditing?(<div className="space-y-4"><div><label className="block text-sm font-medium mb-1.5">Имя</label><input type="text" value={editedProfile.name} onChange={e=>setEditedProfile(p=>({...p,name:e.target.value}))} className="w-full h-10 px-3 rounded-lg border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring" /></div><div><label className="block text-sm font-medium mb-1.5">Телефон</label><input type="tel" value={editedProfile.phone} onChange={e=>setEditedProfile(p=>({...p,phone:e.target.value}))} className="w-full h-10 px-3 rounded-lg border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring" /></div><div className="flex gap-3"><button onClick={()=>setIsEditing(false)} className="flex-1 h-10 rounded-lg border border-input bg-background text-sm font-medium hover:bg-secondary">Отмена</button><button onClick={handleSave} disabled={isSaving} className="flex-1 h-10 rounded-lg bg-primary text-primary-foreground text-sm font-medium disabled:opacity-50 flex items-center justify-center gap-2">{isSaving?<Loader2 className="w-4 h-4 animate-spin" />:<Check className="w-4 h-4" />}Сохранить</button></div></div>):(<div className="space-y-3">{[{icon:User,label:'Имя',value:user.name??'—'},{icon:Mail,label:'Email',value:user.email},{icon:Phone,label:'Телефон',value:user.phone??'—'}].map(f=>(<div key={f.label} className="flex items-center gap-3 p-3 rounded-lg bg-secondary/50"><f.icon className="w-4 h-4 text-muted-foreground" /><div><div className="text-xs text-muted-foreground">{f.label}</div><div className="text-sm font-medium">{f.value}</div></div></div>))}</div>)}</div><button onClick={()=>{logout();window.location.href='/auth'}} className="w-full flex items-center justify-center gap-2 px-4 py-3 rounded-xl border border-destructive/30 text-destructive text-sm font-medium hover:bg-destructive/10"><LogOut className="w-4 h-4" />Выйти из аккаунта</button></div></div>)
}
