"use client"
import { useState, useEffect } from 'react'
import { Plus, Settings2, ArrowLeft, Key, Store, Link2, Check, Loader2, RefreshCw, Trash2 } from 'lucide-react'
import { cn } from '@/lib/utils'
import { storesApi, reviewsApi } from '@/lib/api-client'
import type { Store, CreateStoreRequest } from '@/types'
import { toast } from 'sonner'
type ViewMode = 'list' | 'add-select' | 'add-wb' | 'add-ozon'
export function StoresContent() {
  const [viewMode, setViewMode] = useState<ViewMode>('list')
  const [stores, setStores] = useState<Store[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [syncingId, setSyncingId] = useState<string|null>(null)
  const [wbForm, setWbForm] = useState({ storeName:'', supplierId:'', apiKey:'' })
  const [ozonForm, setOzonForm] = useState({ storeName:'', clientId:'', apiKey:'' })
  const [isSubmitting, setIsSubmitting] = useState(false)
  useEffect(() => { loadStores() }, [])
  const loadStores = async () => { setIsLoading(true); try { setStores(await storesApi.list()) } catch { toast.error('Ошибка загрузки') } finally { setIsLoading(false) } }
  const handleSync = async (id: string) => { setSyncingId(id); try { const r = await reviewsApi.sync({ store_id: id, days_back: 30 }); toast.success(`Синхр: ${r.synced} отзывов`); loadStores() } catch (err) { toast.error(err instanceof Error ? err.message : 'Ошибка') } finally { setSyncingId(null) } }
  const handleDelete = async (id: string) => { if (!confirm('Удалить магазин?')) return; try { await storesApi.delete(id); setStores(p=>p.filter(s=>s.id!==id)); toast.success('Удалён') } catch { toast.error('Ошибка') } }
  const handleAddWB = async (e: React.FormEvent) => { e.preventDefault(); setIsSubmitting(true); try { const s = await storesApi.create({ platform:'wildberries', name:wbForm.storeName, wb_supplier_id:wbForm.supplierId, wb_api_key:wbForm.apiKey }); setStores(p=>[s,...p]); toast.success('WB добавлен'); setViewMode('list'); setWbForm({storeName:'',supplierId:'',apiKey:''}) } catch (err) { toast.error(err instanceof Error ? err.message : 'Ошибка') } finally { setIsSubmitting(false) } }
  const handleAddOzon = async (e: React.FormEvent) => { e.preventDefault(); setIsSubmitting(true); try { const s = await storesApi.create({ platform:'ozon', name:ozonForm.storeName, ozon_client_id:ozonForm.clientId, ozon_api_key:ozonForm.apiKey }); setStores(p=>[s,...p]); toast.success('Ozon добавлен'); setViewMode('list'); setOzonForm({storeName:'',clientId:'',apiKey:''}) } catch (err) { toast.error(err instanceof Error ? err.message : 'Ошибка') } finally { setIsSubmitting(false) } }
  const Field = ({label,value,fkey,ph,icon:Icon,type='text',form,setForm}:{label:string,value:string,fkey:string,ph:string,icon:any,type?:string,form:any,setForm:any}) => (<div><label className="block text-sm font-medium mb-1.5">{label}</label><div className="relative"><Icon className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" /><input type={type} required value={value} onChange={(e:any)=>setForm((p:any)=>({...p,[fkey]:e.target.value}))} placeholder={ph} className="w-full h-10 pl-10 pr-4 rounded-lg border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring" /></div></div>)
  if (viewMode==='add-wb') return (<div className="flex-1 bg-background overflow-auto"><div className="max-w-2xl mx-auto p-8"><button onClick={()=>setViewMode('add-select')} className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-6"><ArrowLeft className="w-4 h-4"/>Назад</button><h1 className="text-xl font-semibold mb-6">Подключить Wildberries</h1><form onSubmit={handleAddWB} className="bg-card rounded-2xl border p-6 space-y-5"><Field label="Название" value={wbForm.storeName} fkey="storeName" ph="Мой магазин" icon={Store} form={wbForm} setForm={setWbForm}/><Field label="ID поставщика" value={wbForm.supplierId} fkey="supplierId" ph="123456" icon={Link2} form={wbForm} setForm={setWbForm}/><Field label="API ключ" value={wbForm.apiKey} fkey="apiKey" ph="eyJhb..." icon={Key} type="password" form={wbForm} setForm={setWbForm}/><div className="flex gap-3"><button type="button" onClick={()=>setViewMode('add-select')} className="flex-1 h-10 rounded-lg border border-input bg-background text-sm font-medium">Отмена</button><button type="submit" disabled={isSubmitting} className="flex-1 h-10 rounded-lg bg-violet-500 text-white text-sm font-medium disabled:opacity-50 flex items-center justify-center gap-2">{isSubmitting?<Loader2 className="w-4 h-4 animate-spin"/>:<Check className="w-4 h-4"/>}{isSubmitting?'Проверка...':'Подключить'}</button></div></form></div></div>)
  if (viewMode==='add-ozon') return (<div className="flex-1 bg-background overflow-auto"><div className="max-w-2xl mx-auto p-8"><button onClick={()=>setViewMode('add-select')} className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-6"><ArrowLeft className="w-4 h-4"/>Назад</button><h1 className="text-xl font-semibold mb-6">Подключить Ozon</h1><form onSubmit={handleAddOzon} className="bg-card rounded-2xl border p-6 space-y-5"><Field label="Название" value={ozonForm.storeName} fkey="storeName" ph="Мой магазин" icon={Store} form={ozonForm} setForm={setOzonForm}/><Field label="Client ID" value={ozonForm.clientId} fkey="clientId" ph="1234567" icon={Link2} form={ozonForm} setForm={setOzonForm}/><Field label="API ключ" value={ozonForm.apiKey} fkey="apiKey" ph="xxxx-xxxx" icon={Key} type="password" form={ozonForm} setForm={setOzonForm}/><div className="flex gap-3"><button type="button" onClick={()=>setViewMode('add-select')} className="flex-1 h-10 rounded-lg border border-input bg-background text-sm font-medium">Отмена</button><button type="submit" disabled={isSubmitting} className="flex-1 h-10 rounded-lg bg-blue-500 text-white text-sm font-medium disabled:opacity-50 flex items-center justify-center gap-2">{isSubmitting?<Loader2 className="w-4 h-4 animate-spin"/>:<Check className="w-4 h-4"/>}{isSubmitting?'Проверка...':'Подключить'}</button></div></form></div></div>)
  if (viewMode==='add-select') return (<div className="flex-1 bg-background overflow-auto"><div className="max-w-2xl mx-auto p-8"><button onClick={()=>setViewMode('list')} className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-6"><ArrowLeft className="w-4 h-4"/>Назад</button><h1 className="text-xl font-semibold mb-6">Выберите маркетплейс</h1><div className="grid grid-cols-2 gap-4">{[{id:'add-wb' as ViewMode,label:'Wildberries',color:'bg-violet-500'},{id:'add-ozon' as ViewMode,label:'Ozon',color:'bg-blue-500'}].map(p=>(<button key={p.id} onClick={()=>setViewMode(p.id)} className="p-6 bg-card rounded-2xl border hover:border-primary/50 hover:shadow-md transition-all text-left"><div className={cn('w-12 h-12 rounded-2xl flex items-center justify-center mb-4',p.color)}><Store className="w-6 h-6 text-white"/></div><div className="font-semibold">{p.label}</div></button>))}</div></div></div>)
  return (<div className="flex-1 bg-background overflow-auto"><div className="max-w-3xl mx-auto p-8"><div className="flex items-center justify-between mb-8"><div><h1 className="text-2xl font-semibold">Магазины</h1></div><button onClick={()=>setViewMode('add-select')} className="flex items-center gap-2 px-4 py-2.5 bg-primary text-primary-foreground rounded-xl text-sm font-medium hover:bg-primary/90"><Plus className="w-4 h-4"/>Добавить</button></div>{isLoading?<div className="flex justify-center py-20"><Loader2 className="w-8 h-8 animate-spin text-muted-foreground"/></div>:stores.length===0?<div className="flex flex-col items-center py-20 text-center"><Store className="w-12 h-12 text-muted-foreground mb-4"/><p className="font-medium mb-2">Нет магазинов</p><button onClick={()=>setViewMode('add-select')} className="flex items-center gap-2 px-4 py-2 bg-primary text-primary-foreground rounded-xl text-sm mt-4"><Plus className="w-4 h-4"/>Добавить</button></div>:<div className="space-y-4">{stores.map(s=>(<div key={s.id} className="bg-card rounded-2xl border p-5 flex items-center justify-between"><div className="flex items-center gap-4"><div className={cn('w-12 h-12 rounded-2xl flex items-center justify-center',s.platform==='wildberries'?'bg-violet-500':'bg-blue-500')}><Store className="w-6 h-6 text-white"/></div><div><div className="font-semibold">{s.name}</div><div className="text-sm text-muted-foreground">{s.platform==='wildberries'?'Wildberries':'Ozon'}{s.last_sync_at&&` · ${new Date(s.last_sync_at).toLocaleDateString('ru-RU')}`}</div></div></div><div className="flex items-center gap-2"><button onClick={()=>handleSync(s.id)} disabled={syncingId===s.id} className="flex items-center gap-2 px-3 py-2 rounded-lg bg-secondary text-sm disabled:opacity-50">{syncingId===s.id?<Loader2 className="w-4 h-4 animate-spin"/>:<RefreshCw className="w-4 h-4"/>}Синхр.</button><button onClick={()=>handleDelete(s.id)} className="p-2 rounded-lg hover:bg-destructive/10 text-muted-foreground"><Trash2 className="w-4 h-4"/></button></div></div>))}</div>}</div></div>)
}
